name: Send pulse reminders for technical authors
on:
    schedule:
        - cron: "42 9 * * 5"

jobs:
    send-reminder:
        runs-on: ubuntu-latest
        steps:
            - name: Send pulse reminders for technical authors
              env:
                WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
              run: |
                WEEK_NUM=`date +"%-V"`
                WEEK_DAY_NUM=`date +"%u"`

                function send_mattermost_msg() {
                  msg="$1"
                  curl -i -X POST \
                    -H 'Content-Type:application/json' \
                    -d "{\"text\": \"$msg\"}" \
                    "$WEBHOOK_URL"
                }

                if [ $(($WEEK_NUM % 2)) -eq 1 ];  # Second week of the pulse. The first pulse of 2025 started in an even week.
                then
                  if [ $(($WEEK_DAY_NUM)) -eq 5 ];  # Friday
                  then
                    msg="@here A reminder that the current pulse ends today\n- Update the status for your Jira cards\n- Schedule work for next pulse. Remember to prioritise work that is part of the cycle roadmap."
                    send_mattermost_msg "$msg"
                  fi
                fi
    send-docpr-value-map-reminder:
        runs-on: ubuntu-latest
        steps:
            - name: Send DOCPR value map reminders for technical authors
              env:
                WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
              run: |
                WEEK_DAY_NUM=`date +"%u"`

                function send_mattermost_msg() {
                  msg="$1"
                  curl -i -X POST \
                    -H 'Content-Type:application/json' \
                    -d "{\"text\": \"$msg\"}" \
                    "$WEBHOOK_URL"
                }

                if if [ $(($WEEK_DAY_NUM)) -eq 4 ];  # every Thursday
                then
                  msg="Friendly reminder to add your DOCPR efforts to the [value map](https://docs.google.com/spreadsheets/d/1QuPgSSicRj8rW_Q05gzKSl6KcYoM8M5RSVvHMnfuw7Q/edit?usp=sharing) :) \n See ["How to use the value map"](https://library.canonical.com/our-organisation/engineering-excellence/documentation/handbook-for-technical-authors/guides-and-explanation/use-value-map) for more information. \n Reach out to the value map gatekeeper (Erin) with any questions!"
                  send_mattermost_msg "$msg"
                fi
#Enable workflow run
