name: Send pulse reminders for technical authors
on:
    schedule:
        - cron: "42 9 * * 5"

jobs:
    send-reminder:
        runs-on: ubuntu-latest
        steps:
            - name: Send pulse reminders for technical authors
              env:
                WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
              run: |
                WEEK_NUM=`date +"%-V"`
                WEEK_DAY_NUM=`date +"%u"`

                function send_mattermost_msg() {
                  msg="$1"
                  curl -i -X POST \
                    -H 'Content-Type:application/json' \
                    -d "{\"text\": \"$msg\"}" \
                    "$WEBHOOK_URL"
                }

                if [ $(($WEEK_NUM % 2)) -eq 1 ];  # Second week of the pulse. The first pulse of 2025 started in an even week.
                then
                  if [ $(($WEEK_DAY_NUM)) -eq 5 ];  # Friday
                  then
                    msg="@here A reminder that the current pulse ends today\n- Update the status for your Jira cards\n- Schedule work for next pulse. Remember to prioritise work that is part of the cycle roadmap."
                    send_mattermost_msg "$msg"
                  fi
                fi
#Enable workflow run
